"""empty message

Revision ID: 918d0e2e3c96
Revises: fc2e6c2d5172
Create Date: 2023-10-26 01:43:47.317908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918d0e2e3c96'
down_revision: Union[str, None] = 'fc2e6c2d5172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reservation', sa.Column('selection', sa.BIGINT(), nullable=True))
    op.add_column('user_reservation', sa.Column('delivery_type', sa.VARCHAR(length=24), nullable=False))
    op.add_column('user_reservation', sa.Column('user_name', sa.VARCHAR(length=128), nullable=False))
    op.add_column('user_reservation', sa.Column('address', sa.VARCHAR(length=256), nullable=True))
    op.add_column('user_reservation', sa.Column('phone_number', sa.VARCHAR(length=24), nullable=False))
    op.drop_column('user_reservation', 'number_guests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reservation', sa.Column('number_guests', sa.SMALLINT(), nullable=False))
    op.drop_column('user_reservation', 'phone_number')
    op.drop_column('user_reservation', 'address')
    op.drop_column('user_reservation', 'user_name')
    op.drop_column('user_reservation', 'delivery_type')
    op.drop_column('user_reservation', 'selection')
    # ### end Alembic commands ###
